Make logging configurable.
juju/charmstore pull request #705
Opened 2017-02-09 10:58 UTC by fabricematrat

2017-02-09 11:03 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2024/

2017-02-09 11:10 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2025/

2017-02-09 16:08 UTC, mhilton requested changes
Generally pretty good, but I'd like a couple of changes.

2017-02-09 16:08 UTC, mhilton commented on cmd/charmd/main.go
> -	loggingConfig = flag.String("logging-config", "", "specify log levels for modules e.g. <root>=TRACE")
leave the flag, it's probably been set on some server somewhere.

2017-02-09 16:08 UTC, mhilton commented on config/config.go
> +	LoggingLevel      string          `yaml:"logging-level"`
Please update the test for this.

2017-02-09 16:09 UTC, jrwren approved these changes
I'm tempted to suggest that the -logging-config option should be kept and used to override the config file option, to prevent breaking anything that uses that option, but I don't think its use is widespread enough, so nevermind. I mention it here in case I'm wrong, everyone can point and say, "shoulda... even thought about it..." and we can all cry about it together.

2017-02-10 08:30 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2026/

2017-02-10 08:34 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore/2027/

2017-02-10 09:06 UTC, mhilton approved these changes
LGTM

2017-02-13 08:38 UTC, closed without merging