Bump juju/utils dependency w/ fixes.
juju/charmstore pull request #784
Opened 2018-02-08 02:34 UTC by Veebers

Bumped juju/utils version in juju/juju which broke charmstore.v5-unstable due to API changes.

Update charmstore.v5-unstable in regards to those API changes (as well as bump the juju/utils version to match too).

2018-02-08 02:35 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2168/

2018-02-11 19:52 UTC, Veebers commented
I'm not sure why this is failing in CI, seems it's not pulling the deps for juju/utils? The tests pass for me when I run them locally (in a lxd container) using the Makefile provided commands.

2018-02-13 13:14 UTC, mhilton commented
It looks like you're missing a dependency on gopkg.in/juju/httprequest.v1 `make create-deps` should sort that out for you.

2018-02-14 02:23 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2169/

2018-02-14 02:25 UTC, Veebers commented
@mhilton Ah I see, thanks for clarifying for me :-)

2018-02-14 05:34 UTC, mhilton requested changes
The code that's there is fine but if you could just do a little housekeeping that would be great.

2018-02-14 05:34 UTC, mhilton commented on dependencies.tsv
> +gopkg.in/httprequest.v1	git	35158f716c228fdf58b5a5b80cf331302d10160a	2017-11-03T09:19:05Z
This unfortunately means there are two versions of this package linked in the code (the other being github.com/juju/httprequest). I've checked and the use of that package in the charmstore code itself is fairly limited. Could you please update the instances of the old package with the new one?

2018-02-16 03:49 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2170/

2018-02-16 04:46 UTC, jujugui commented
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore/2171/

2018-02-16 04:48 UTC, Veebers commented
*phew* OK I got there in the end.

I had to take into account the change from httprequest.ErrorMapper as well as update the expected strings in the test (due to the difference betweeen juju/httprequest and httprequest.v1 error message format).

2018-02-20 10:40 UTC, mhilton approved these changes
LGTM

2018-02-20 11:31 UTC, rogpeppe commented
LGTM

2018-02-20 12:05 UTC, rogpeppe commented
:shipit:

2018-02-20 12:06 UTC, jujugui commented
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-merge

2018-02-20 12:09 UTC, merged